### ISSUE TITLE
docker

### ISSUE THREAD

**Issue by liuxianliang-icrc** [melobio/EvoPlay#1]
Hi, I can pull the docker image from your comand "docker pull licko789/evoplay:latest", it says that "Error response from daemon: pull access denied for licko789/evoplay, repository does not exist or may require 'docker login': denied: requested access to the resource is denied". How can I fix the error?

**Comment by melobio** [comment]
Hi, you can try "docker pull licko789/evozero:latest"

**Comment by liuxianliang-icrc** [comment]
Thank you!
