### ISSUE TITLE
How to set the starting sequences for binder design 1ssc

### ISSUE THREAD

**Issue by CNDOTA** [melobio/EvoPlay#10]
Dear authors,

Very interesting and impressive work! I want to ask for help from you.

In Fig 3 (c),  there are five starting sequences for the binder design task of 1ssc.

<img width="561" alt="1708438007038" src="https://github.com/melobio/EvoPlay/assets/17664058/f4de23d6-7595-412d-95e6-ae4fc52093a2">

I want to know how to set the five starting sequences. Is it set by the parameters such as init_num or start_sequence?

Could you give detailed instructions or the exact starting sequences for the binder design task of 1ssc?

Thank you very much!

**Comment by CNDOTA** [comment]
Another problem is the c_puct value for the peptide design task. Could you provide this value in the peptide design tasks? Thank you very much!

**Comment by CNDOTA** [comment]
Dear authors,

I try to follow the peptide binder design task 1ssc and have tried some hyperparameters settings but cannot reach the performance in the paper.

Here are my hyperparameters which try to follow the settings described in the paper for peptide binder design task 1ssc.

{
  "output_dir": "../../results/EvoZero_output/",
  "start_sequence": "CKQRSLCYHLS",
  "pdbid": "1ssc",
  "n_playout": 22,
  "init_num": "1",
  "batch_size": 32,
  "recycle_num": 0,
  "niter": 1000,
  "jumpout": 6,
  "c_puct": 0.5,
  "sleep": 1,
  "ids": "../../data/peptide_data/LNR_set_12sub.csv",
  "idx": "1",
  "method": "evoplay",
  "gpus": "0"
}

Could you please figure out what I missed?

Thank you very much!

**Comment by wangyi880907** [comment]
1. the performance of the method can not be judged only from the settings above, 
2. plddt is highly sensitive with respect to the input MSA, nevertheless with frequent updating of the databases of AF2,
3. the paper does not pursuit a fixed set of hyperparameters as a golden standard setting; instead, the setting should be readjusted according to specific implementation of optimizing environment, gaining curves, etc.
4. Any optimizing algorithm should be test multiple times to evaluate.
5. To align the AF2 setting, comparison with other optimizing methods such as mcmc should also be implemented to make prevent the influence of wrong AF2 settings.

**Comment by wangyi880907** [comment]
the performance of the method can not be judged only from the settings above,
plddt is highly sensitive with respect to the input MSA, nevertheless with frequent updating of the databases of AF2,
the paper does not pursuit a fixed set of hyperparameters as a golden standard setting; instead, the setting should be readjusted according to specific implementation of optimizing environment, gaining curves, etc.
Any optimizing algorithm should be test multiple times to evaluate.
To align the AF2 setting, comparison with other optimizing methods such as mcmc should also be implemented to  prevent the influence of wrong AF2 settings.
