### ISSUE TITLE
oracle weight

### ISSUE THREAD

**Issue by ruihan-dong** [melobio/EvoPlay#3]
Hi, 

Thanks for your fascinating work.
The figshare link under data/Oracle_weight is the same as GB1_PhoQ_data. Could you provide the right link for the oracle weight files?

**Comment by melobio** [comment]
We have addressed the issue you pointed out. The weight of this oracle is derived from publicly available data. You can access this information by executing the [download_landscape.sh](https://github.com/HeliXonProtein/proximal-exploration/blob/main/download_landscape.sh) script, available at [HeliXonProtein's proximal-exploration repository on GitHub](https://github.com/HeliXonProtein/proximal-exploration). This will enable you to obtain the oracle weight files for eight datasets, including the weight files for the GFP and PAB1 datasets, which are referenced in our article.

**Comment by ruihan-dong** [comment]
Got it. Thanks!
