### ISSUE TITLE
GB1&PhoQ data is shared privately

### ISSUE THREAD

**Issue by zju-wyh** [melobio/EvoPlay#6]
![image](https://github.com/melobio/EvoPlay/assets/103970426/9ad7417d-913e-498f-8957-c8ec7d00f20d)
GB1&PhoQ data is shared privately, and can not downloaded.

**Comment by melobio** [comment]
Thanks!
We have addressed the issue you pointed out. 

![image](https://github.com/melobio/EvoPlay/assets/82862879/a31c699b-b820-49a3-b19e-1097f713aaa2)

**Comment by zju-wyh** [comment]
sorry，It can not be downloaded.

**Comment by zju-wyh** [comment]
> Thanks! We have addressed the issue you pointed out.
> 
> ![image](https://user-images.githubusercontent.com/82862879/266888253-a31c699b-b820-49a3-b19e-1097f713aaa2.png)
sorry，It can not be downloaded.

**Comment by zju-wyh** [comment]
> Thanks! We have addressed the issue you pointed out.
> 
> ![image](https://user-images.githubusercontent.com/82862879/266888253-a31c699b-b820-49a3-b19e-1097f713aaa2.png)

sorry，It can not be downloaded.

**Comment by zju-wyh** [comment]
> Thanks! We have addressed the issue you pointed out.
> 
> ![image](https://user-images.githubusercontent.com/82862879/266888253-a31c699b-b820-49a3-b19e-1097f713aaa2.png)

![image](https://github.com/melobio/EvoPlay/assets/103970426/3a4d681c-cac7-44dd-a33a-fe232c9c59db)
sorry，It can not be downloaded.

**Comment by zju-wyh** [comment]
> Thanks! We have addressed the issue you pointed out.
> 
> ![image](https://user-images.githubusercontent.com/82862879/266888253-a31c699b-b820-49a3-b19e-1097f713aaa2.png)
![1695039668235](https://github.com/melobio/EvoPlay/assets/103970426/4fd3fc1c-4770-481c-84f6-e7c7d6923ba8)
sorry，It can not be downloaded.

**Comment by zju-wyh** [comment]
> Thanks! We have addressed the issue you pointed out.
> 
> ![image](https://user-images.githubusercontent.com/82862879/266888253-a31c699b-b820-49a3-b19e-1097f713aaa2.png)

![1695039668235](https://github.com/melobio/EvoPlay/assets/103970426/8c3cc777-e4af-45d0-a50d-ea84ac527e9a)
sorry，It can not be downloaded.
